// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"YEP_SaveEventLocations","status":true,"description":"v1.06 Enable specified maps to memorize the locations of\r\nevents when leaving and loading them upon reentering map.","parameters":{}},
{"name":"GALV_MapProjectiles","status":true,"description":"(v.1.8) Create projectiles that can interact with the map and map characters","parameters":{"Tile Size":"48","Fade Speed":"40","Disable Mouse Move":"false","Premade 1":"","Premade 2":"","Premade 3":"","Premade 4":"","Premade 5":"","Premade 6":"","Premade 7":"","Premade 8":"","Premade 9":"","Premade 10":"","Premade 11":"","Premade 12":"","Premade 13":"","Premade 14":"","Premade 15":"","Premade 16":"","Premade 17":"","Premade 18":"","Premade 19":"","Premade 20":""}},
{"name":"DFS_Keymap","status":true,"description":"This plugin ables new keymap: WASD and V","parameters":{}},
{"name":"ShakeScreen","status":true,"description":"Simply shakes the screen","parameters":{}},
{"name":"TSR_MoveEvent","status":true,"description":"v1.4.0 This plugin allow to push, pull, pick-up and throw events.","parameters":{"Move Key":"ok","Move Event Offset":"12","Pickup Event Offset":"24","Effort Balloon Id":"11","Move Frame Rate":"4","---Sounds":"","Effort Sound":"","Push Sound":"push4, 100, 100, 0","Mystery Music Effect":"","Pickup Sound":"","Throw Sound":"","Drop Sound":"","---Motion images":"","Pushing Character Image":"","Pulling Character Image":"","Pickup Character Image":"","Throw Character Image":""}},
{"name":"HIME_CommonEventButtons","status":true,"description":"v1.1 - Allows you to execute common events with the press of a \r\nbutton on the map.","parameters":{}},
{"name":"SRD_ShakingText","status":true,"description":"Allows you to add Shaking Text to your Show Text events!","parameters":{"Reset Shaking per Box":"true","Default Shaking Power":"$.randomNum(0.2, 0.3)","Default Shaking Max":"0.5","Default Wave Power":"0.5","Default Wave Max":"2","Default Slide Power":"0.5","Default Slide Max":"4","Copy Outline":"true"}}
];
